# font_family      Maple Mono NF CN
# bold_font        Maple Mono NF CN Bold
# italic_font      Maple Mono NF CN Italic
# bold_italic_font Maple Mono NF CN BoldItalic
font_size        18
editor nvim
shell /bin/zsh
background_opacity 0.9
hide_window_decorations titlebar-only

window_padding_width 5

map cmd+b send_text all \x1bb
map cmd+f send_text all \x1bf
map cmd+d send_text all \x1bd

allow_remote_control socket-only
listen_on unix:/tmp/mykitty


# BEGIN_KITTY_FONTS
font_family      family='Maple Mono NF CN' style='Medium Italic'
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Scroll & rendering performance
# Ref: https://sw.kovidgoyal.net/kitty/performance/
# Minimize latency at the cost of increased energy usage
sync_to_monitor no
input_delay 0
repaint_delay 2
wheel_scroll_multiplier 3.0
wheel_scroll_min_lines 1
touch_scroll_multiplier 1.0
scrollback_lines 5000
cursor_blink_interval 0
